name: CI Build with Gradle

on:
  push:
    branches: [ "main" ]

jobs:
  Gradle-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: EndercubeProxyPlugin
          path: build/libs/EndercubeProxyPlugin-*.*.*.jar